### ISSUE TITLE
[Feature] 로더

### ISSUE THREAD

**Issue by hyeon-po** [peterosea/eham-campus#44]
https://app.moqups.com/dA0dp2rCP4/view/page/ae268c107

- [x] issue1

**Comment by eungook-jlab** [comment]
내일 풀리퀘때 반영됩니다. 감사합니다.

**Comment by hyeon-po** [comment]
@eungook-jlab 

해당페이지는 데모이지만 이것을 로더로 사용하려했습니다. data 파일만 전해드리면 될까요?
https://wp.ehamcampus.com/loader/

**Comment by eungook-jlab** [comment]
@hyeon-po 
번거로우시겠지만 단독으로 브라우저에 출력될 수 있는 html과 css 형태로 부탁 드립니다. 감사합니다.
