### ISSUE TITLE
[BUG] exihibition scroll-x over

### ISSUE THREAD

**Issue by hyeon-po** [peterosea/eham-campus#45]
https://github.com/peterosea/eham-campus/blob/dd1adebf6392f00e2465e52f35bce4a6865f4ce5/pages/exhibition/current.js#L434-L435
https://app.moqups.com/dA0dp2rCP4/view/page/a280fe047

@eungook-jlab 
해당 부분 스타일이 block 이어서 위 이슈가 나오는 것같습니다.

**Comment by eungook-jlab** [comment]
확인해 보겠습니다. 감사합니다.

**Comment by eungook-jlab** [comment]
@hyeon-po 
이 부분 https://app.moqups.com/dA0dp2rCP4/view/page/a3374bb3e 의 2번 이슈 말씀이 맞는지 확인 부탁 드립니다

**Comment by hyeon-po** [comment]
@eungook-jlab 
맞습니다
.appear block이어서 appear 인 돔의 :after 로만든 content가 넘쳐서 스크롤이 생기는 것으로 봤습니다.
![](http://wp.ehamcampus.com/wp-content/uploads/스크린샷-2020-03-18-오전-10.44.27.png)

**Comment by eungook-jlab** [comment]
@hyeon-po 
넵 스크린샷과 함께 자세한 설명 감사합니다.

**Comment by eungook-jlab** [comment]
@hyeon-po 
#49를 통해 해결 되었습니다.
https://eham-campus-git-eungook-0317b.peterosea.now.sh

확인 후 이슈 종료를 부탁 드립니다. 감사합니다.
